version: 2.1

jobs:
  build:
    docker:
      - image: circleci/python:3.7.10-stretch
    steps:
      - checkout

      - run: "poetry install"

      - setup_remote_docker:
          version: 20.10.6
          docker_layer_caching: true